version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_dataset_definition:
    run: ehrql:v0
      generate-dataset
      --output output/dataset.arrow
      analysis/dataset_definition.py
    outputs:
      highly_sensitive:
        dataset: output/dataset.arrow

  count_events:
    needs: [generate_dataset_definition]
    run: python:latest python analysis/count_events.py
    outputs:
      highly_sensitive:
        count: output/total_subcutaneous_morphine_events.txt
